apiVersion: v1
kind: Secret
metadata:
  name: cred
  namespace: valaxy
data:
  .dockerconfigjson:  ewoJImF1dGhzIjogewoJCSJ2YWxheHk0Njk4Lmpmcm9nLmlvIjogewoJCQkiYXV0aCI6ICJZVzFoY21GMllYUm9hVHBCYldGeVlYWmhkR2hwTkM1aSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson